User.destroy_all

users_created = [
  {
    first_name: "Garrett",
    last_name: "G",
    email: "gg@school.edu",
    created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    user_id: 1,
    password: 'pw123456',
    reset_password_token: nil,
    reset_password_sent_at: nil,
    remember_created_at: nil
  },
  {
    first_name: "Kelly",
    last_name: "R",
    email: "kr@school.edu",
    created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    user_id: 2,
    password: 'pw123456',
    reset_password_token: nil,
    reset_password_sent_at: nil,
    remember_created_at: nil
  },
  {
    first_name: "Bennett",
    last_name: "K",
    email: "bk@school.edu",
    created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    user_id: 3,
    password: 'pw123456',
    reset_password_token: nil,
    reset_password_sent_at: nil,
    remember_created_at: nil
  },
  {
    first_name: "Jake",
    last_name: "L",
    email: "jl@school.edu",
    created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
    user_id: 4,
    password: 'pw123456',
    reset_password_token: nil,
    reset_password_sent_at: nil,
    remember_created_at: nil
  }
]

users_objects = []

users_created.each do |user|
  user_made = User.create!(user)
  users_objects.append(user_made)
end

p "Created #{User.count} users"

Entry.destroy_all


users = User.all

Entry.create!([{
  title: "Lava Everywhere",
  description: "I woke up and the world was on fire; I couldn't believe it. A huge volcano suddenly appeared outside my house and lava was spewing in all directions.",
  keyword: "lava",
  user_id: 1,
  user: users[0],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("12/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("12/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Bats in my House",
  description: "A lot of bats appeared out of nowhere. I'm not sure if it's because I was the Riddler for Halloween, or if I had a lot of insects to feed my bearded dragon later",
  keyword: "bat",
  user_id: 2,
  user: users[1],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/11/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/13/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Tables and chairs",
  description: "My friend was debating me over which came first: tables or chairs? I thought it was stupid...not sure how I remebered this",
  keyword: "furniture",
  user_id: 3,
  user: users[2],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/04/2021 09:30", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 10:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Talking Dolphins",
  description: "I woke up, went to school, and everyone there was a dolphin. I ran to the bathroom to see what I looked like, and sure enough, I was too.",
  keyword: "dolphin",
  user_id: 4,
  user: users[3],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/22/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/23/2021 10:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Mamma Mia, but scary",
  description: "I love the movie Mamma Mia, but when my friends and I watched it for Halloween it got...spooky. No more happy ending, that\'s for sure.",
  keyword: "musical",
  user_id: 1,
  user: users[0],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Computer Mishap",
  description: "I was casually sitting in class, playing Flappy Golf (as one does), but my computer began to talk to me...as if it was disappointed in me. I know I'm bad at Flappy Golf, but come on, give me a break!!",
  keyword: "technology",
  user_id: 2,
  user: users[1],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/13/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/22/2021 11:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Falling...",
  description: "It was one of those dreams where you're falling for a while and then suddenly hit the ground. I woke up and was legit boutta throw hands.",
  keyword: "falling",
  user_id: 3,
  user: users[2],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Harry Potter Snow World",
  description: "Snow world. We were in the Room of Requirement from Harry Potter and it's snowy all over. Picture Voldemort in a Santa costume sreaming at us, throwing green spells the entire time. Wild.",
  keyword: "wizard",
  user_id: 4,
  user: users[3],
  is_anon: false,
  is_private: false,
  created_at: DateTime.strptime("11/30/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("12/03/2021 12:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Dinosaurs and the Louvre",
  description: "This probably happened because of my love for dinosaurs and art. It was like a Met Gala, but in the Louvre and everyone was a dinosaur.",
  keyword: "dinosaur",
  user_id: 1,
  user: users[0],
  is_anon: true,
  is_private: true,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Flappy Bird, but Squid Game",
  description: "I was put into a room like the people were in Squid Game, except instead of playing silly childhood games, we were forced to play Flappy Bird. I got to about 20, died, looked up, and...woke up!",
  keyword: "flappy",
  user_id: 2,
  user: users[1],
  is_anon: true,
  is_private: true,
  created_at: DateTime.strptime("11/17/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/20/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Computer Nightmare",
  description: "I woke up (in my dream) and looked over to expect my computer sitting quietly on my table, quietly, but it was howling! I have no clue why the fan was being like that...so silly.",
  keyword: "technology",
  user_id: 3,
  user: users[2],
  is_anon: true,
  is_private: true,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Middle School Drama All Over Again",
  description: "I was in my 8th grade science class with Mr. Clemmons and was being yelled at by him. I get it, but I just had to point out the little bit of whiteboard marker he didn\'t erase!",
  keyword: "drama",
  user_id: 4,
  user: users[3],
  is_anon: true,
  is_private: true,
  created_at: DateTime.strptime("11/04/2021 07:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "My Future, Hopefully?",
  description: "It seemed like I was making a standard commute to work – not by train or car, but by bike!",
  keyword: "commute",
  user_id: 1,
  user: users[0],
  is_anon: true,
  is_private: false,
  created_at: DateTime.strptime("11/10/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/10/2021 11:00", "%m/%d/%Y %H:%M"),
},
{
  title: "2012, the Movie, but Real",
  description: "Title says it all. If you\'ve never seen the movie, well...that\'s honestly fine because it\'s not great. But the premise is there!",
  keyword: "apocalypse",
  user_id: 2,
  user: users[1],
  is_anon: true,
  is_private: false,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "The Greatest Music Lesson in History!",
  description: "My favorite composer, John Williams, was teaching me 1-on-1 about composition! I love film scores, so this was a huge moment for me.",
  keyword: "composition",
  user_id: 3,
  user: users[2],
  is_anon: true,
  is_private: false,
  created_at: DateTime.strptime("12/07/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("12/08/2021 10:30", "%m/%d/%Y %H:%M"),
},
{
  title: "Sunday Scaries",
  description: "I got really stressed out the day before an exam and...made a fool of myself",
  keyword: "embarrassment",
  user_id: 4,
  user: users[3],
  is_anon: true,
  is_private: false,
  created_at: DateTime.strptime("11/05/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/24/2021 09:30", "%m/%d/%Y %H:%M"),
},
{
  title: "Backpacks Wearing Humans?",
  description: "It was like one of those Rick and Morty alternate universes – the Backpacks were talking from their little top pouches and were just hovering around, stuffing humans with their school supplies. I was a backpack too...",
  keyword: "backpacks",
  user_id: 1,
  user: users[0],
  is_anon: false,
  is_private: true,
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Nothing to See Here...",
  description: "Just kidding!! This dream was insane – but I don't remember any of it oops...something about Pokemon making humans fight?",
  keyword: "pokemon",
  user_id: 2,
  user: users[1],
  is_anon: false,
  is_private: true,
  created_at: DateTime.strptime("11/09/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/10/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Super Smash Bros. Tournament",
  description: "I was as good as Mang0! My wavedashes, shield drops, L-cancels, and the works were on fire. But then I played an ice climbers and got wobbled and JV-5 stocked...",
  keyword: "smash",
  user_id: 3,
  user: users[2],
  is_anon: false,
  is_private: true,
  created_at: DateTime.strptime("11/11/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/12/2021 10:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Soaring over the Seas",
  description: "I could fly! It was like I was invincible – except without all of the violence and gore. Phew!",
  keyword: "flight",
  user_id: 4,
  user: users[3],
  is_anon: false,
  is_private: true,
  created_at: DateTime.strptime("11/04/2021 08:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 08:30", "%m/%d/%Y %H:%M"),
}])

p "Created #{Entry.count} entries"