User.destroy_all

User.create!([{
  first_name: "Garrett",
  last_name: "Gilliom",
  email: "ggilliom@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 1,
},
{
  first_name: "Kelly",
  last_name: "Romer",
  email: "kromer@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 2,
},
{
  first_name: "Bennett",
  last_name: "Kahn",
  email: "bkahn@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 3,
},
{
  first_name: "Jake",
  last_name: "Lehner",
  email: "jlehner@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 4,
},
{
  first_name: "Nathan",
  last_name: "Fillion",
  email: "nfillion@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 5,
},
{
  first_name: "Michelle",
  last_name: "Obama",
  email: "mobama@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 6,
},
{
  first_name: "Mr.",
  last_name: "Clean",
  email: "mrclean@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 7,
},
{
  first_name: "Bruce",
  last_name: "Banner",
  email: "bbanner@outlook.com",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 8,
},
{
  first_name: "Steve",
  last_name: "Rogers",
  email: "srogers12@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 9,
},
{
  first_name: "Clark",
  last_name: "Kent",
  email: "ckent5@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 10,
},
{
  first_name: "Andrew",
  last_name: "Smith",
  email: "bkahn@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 11,
},
{
  first_name: "Dylan",
  last_name: "Moneyman",
  email: "dmoneyman@gmail.com",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 12,
},
{
  first_name: "Jack",
  last_name: "Terran",
  email: "jterran@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 13,
},
{
  first_name: "Jill",
  last_name: "Biden",
  email: "jbiden@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 14,
},
{
  first_name: "Anastasia",
  last_name: "Kurdia",
  email: "akurdia@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 15,
},
{
  first_name: "Margot",
  last_name: "Robbie",
  email: "mrobbie@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 16,
},
{
  first_name: "Chris",
  last_name: "Pine",
  email: "cpine@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 17,
},
{
  first_name: "Evan",
  last_name: "Daley",
  email: "edaley@tulane.edu",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 18,
},
{
  first_name: "Drew",
  last_name: "Brees",
  email: "dbress@saints.com",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 19,
},
{
  first_name: "Zion",
  last_name: "Williamson",
  email: "zwilliamson@pelicans.com",
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  user_id: 20,
}])

p "Created #{User.count} users"

Entry.destroy_all

Entry.create!([{
  title: "Lava Everywhere",
  description: "I woke up and the world was on fire; I couldn't believe it. A huge volcano suddenly appeared outside my house and lava was spewing in all directions.",
  keyword: "lava",
  user_id: 1,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Bats in my House",
  description: "A lot of bats appeared out of nowhere. I'm not sure if it's because I was the Riddler for Halloween, or if I had a lot of insects to feed my bearded dragon later",
  keyword: "bat",
  user_id: 2,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Tables and chairs",
  description: "My friend was debating me over which came first: tables or chairs? I thought it was stupid...not sure how I remebered this",
  keyword: "furniture",
  user_id: 3,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Talking Dolphins",
  description: "I woke up, went to school, and everyone there was a dolphin. I ran to the bathroom to see what I looked like, and sure enough, I was too.",
  keyword: "dolphin",
  user_id: 4,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Mamma Mia, but scary",
  description: "I love the movie Mamma Mia, but when my friends and I watched it for Halloween it got...spooky. No more happy ending, that\'s for sure.",
  keyword: "Mamma Mia",
  user_id: 5,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Computer Mishap",
  description: "I was casually sitting in class, playing Flappy Golf (as one does), but my computer began to talk to me...as if it was disappointed in me. I know I'm bad at Flappy Golf, but come on, give me a break!!",
  keyword: "technology",
  user_id: 6,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Falling...",
  description: "It was one of those dreams where you're falling for a while and then suddenly hit the ground. I woke up and was legit boutta throw hands.",
  keyword: "falling",
  user_id: 7,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Harry Potter Snow World",
  description: "Snow world. We were in the Room of Requirement from Harry Potter and it's snowy all over. Picture Voldemort in a Santa costume sreaming at us, throwing green spells the entire time. Wild.",
  keyword: "snow",
  user_id: 8,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Dinosaurs and the Louvre",
  description: "This probably happened because of my love for dinosaurs and art. It was like a Met Gala, but in the Louvre and everyone was a dinosaur.",
  keyword: "dinosaur",
  user_id: 9,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Flappy Bird, but Squid Game",
  description: "I was put into a room like the people were in Squid Game, except instead of playing silly childhood games, we were forced to play Flappy Bird. I got to about 20, died, looked up, and...woke up!",
  keyword: "flappy bird",
  user_id: 10,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Computer Nightmare",
  description: "I woke up (in my dream) and looked over to expect my computer sitting quietly on my table, quietly, but it was howling! I have no clue why the fan was being like that...so silly.",
  keyword: "computer",
  user_id: 11,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Middle School Drama All Over Again",
  description: "I was in my 8th grade science class with Mr. Clemmons and was being yelled at by him. I get it, but I just had to point out the little bit of whiteboard marker he didn\'t erase!",
  keyword: "middle school",
  user_id: 12,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "My Future, Hopefully?",
  description: "It seemed like I was making a standard commute to work – not by train or car, but by bike!",
  keyword: "commute",
  user_id: 13,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "2012, the Movie, but Real",
  description: "Title says it all. If you\'ve never seen the movie, well...that\'s honestly fine because it\'s not great. But the premise is there!",
  keyword: "apocalypse",
  user_id: 14,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "The Greatest Music Lesson in History!",
  description: "My favorite composer, John Williams, was teaching me 1-on-1 about composition! I love film scores, so this was a huge moment for me.",
  keyword: "composition",
  user_id: 15,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Sunday Scaries",
  description: "I got really stressed out the day before an exam and...made a fool of myself",
  keyword: "embarrassment",
  user_id: 16,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Backpacks Wearing Humans?",
  description: "It was like one of those Rick and Morty alternate universes – the Backpacks were talking from their little top pouches and were just hovering around, stuffing humans with their school supplies. I was a backpack too...",
  keyword: "backpacks",
  user_id: 17,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Nothing to See Here...",
  description: "Just kidding!! This dream was insane – but I don't remember any of it oops...something about Pokemon making humans fight?",
  keyword: "pokemon",
  user_id: 18,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Super Smash Bros. Tournament",
  description: "I was as good as Mang0! My wavedashes, shield drops, L-cancels, and the works were on fire. But then I played an ice climbers and got wobbled and JV-5 stocked...",
  keyword: "smash",
  user_id: 19,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
},
{
  title: "Soaring over the Seas",
  description: "I could fly! It was like I was invincible – except without all of the violence and gore. Phew!",
  keyword: "flight",
  user_id: 20,
  time: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  created_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
  updated_at: DateTime.strptime("11/04/2021 09:00", "%m/%d/%Y %H:%M"),
}])

p "Created #{Entry.count} entries"